### ISSUE TITLE
Make pictures larger to fill up screen

### ISSUE THREAD

**Issue by loganbrunner** [it4paddlers/river-photo-gauge#11]
Right now there are gutters and padding, make this fill more of the screen.

Have the 3 reference images in one row as well.

**Comment by loganbrunner** [comment]
Come to the issue where you could have a massive picture that goes beyond the browser, which is not ideal. Could have a little settings option with "+" and "-" which would allow the user to determine the image size.

**Comment by loganbrunner** [comment]
Updated with e8be0b8

**Comment by loganbrunner** [comment]
Updated with e8be0b8

**Comment by sirtet** [comment]
Looks good on mobile, not so on desktop:
![image](https://user-images.githubusercontent.com/3509308/163950467-d23f4e2e-8db3-4960-bf3e-fc9705c4c7ef.png)
I think if the layout stays as on mobile, the widest thing on the page should be the main image.

**Comment by sirtet** [comment]
But as Desktop screens are typically landscape, i'd suggest to put the ref-images to the right again, same as the initial prototype did.
Use some auto-scale so the main- & ref- images fill up all available space, limited to viewport- width & height, so no overflow will happen.

**Comment by loganbrunner** [comment]
Yes, I think the mobile is fine as is since the 3 little images can fit nicely under the one wide photo:
<img width="328" alt="Screen Shot 2022-04-19 at 7 48 35 PM" src="https://user-images.githubusercontent.com/14346184/163952668-dfc531fd-5a31-4db5-853c-1140b22c1827.png">


Yeah, i like the ref images being to the right on desktop. will have to see how the auto-scale thing works, that might be beyond my knowledge, but i can try to get it to fit ;)

**Comment by loganbrunner** [comment]
a984116 - Adjusted to have ref images on the side for tablet and computer, and then reference images below the main image for mobile.

**Comment by loganbrunner** [comment]
Merged to main so closing.
