### ISSUE TITLE
Format date to be more human readable.

### ISSUE THREAD

**Issue by sirtet** [it4paddlers/river-photo-gauge#12]
replace 2021-10-26, 10:36:00
with sth. like Mo. Jan. 5, 2022
or Jan. 5, 2022 (Monday)
or whatever the internet recommends for human readable date with weekday...
(I think the weekday is quite usefull because one tends to remember "i was a saturday end of august" rather than the exact date.)

**Comment by loganbrunner** [comment]
Updated this with f7ee129. Is this any better, @sirtet?

**Comment by sirtet** [comment]
perfect...
