### ISSUE TITLE
Limit height of reference-images box to height of current-image

### ISSUE THREAD

**Issue by sirtet** [it4paddlers/river-photo-gauge#17]
![image](https://user-images.githubusercontent.com/3509308/164012731-52a20415-8a8c-4c3f-9af4-731fc3afcbec.png)

Have the rev-images in a Box that's the same height as the current image, and set each image to ~1/3 height of that box?

**Comment by loganbrunner** [comment]
The alternative is that we don't set a max size for the main image - see this picture:
![Screen Shot 2022-04-20 at 6 55 23 PM](https://user-images.githubusercontent.com/14346184/164168631-b075b593-c64b-42cc-a7e8-9e56e5032d6b.png)

Is that a better option?

**Comment by sirtet** [comment]
not sure what u mean. What's defining the size here? Sure, better. But there's already scrolling with your aspect ratio, i have a ultrawide monitor, so would i only see low and parts of med. ref-img?
I thought to set max-h & -v to the container of all images, so it will stay always within VP.

**Comment by sirtet** [comment]
fixed in V2 branch
