### ISSUE TITLE
Define UI for showing reference pictures

### ISSUE THREAD

**Issue by sirtet** [it4paddlers/river-photo-gauge#6]
The presentation of current and past pictures is straight forward: A slideshow with prev-next buttons and a way to select a date-range.
Maybe a slider to allow sliding through the selection like through a video clip.
(a future improvement idea is to convert the images to a video, to benefit from inter-frame compression).
We want the pics to change without any effects, so one clearly sees which pixels change from pic to pic, in other words, how the water level compares from pic to pic.

But we have to decide how to present the reference pics and how the user interacts with them.
As we know no "prior art" to look at for that, we might need to test a number of ideas to find out what's good and what's not.

Basic considerations:

1. Same as comparing 2 pics in the timeline, the main objective is to easily see the difference in waterlevel.
So this asks for a way to temporarly replace the currently shown timeline-pic. with the reference-pic of interest.

2. At least in the beginning of a new gauge, there won't always be ideal pics for MIN MID MAX, so we probably need captions for the ref-pics, eg. "High side of medium" "Flood" "too low by 10cm" etc.
3. For the same reason as in 2. we might end up with 1 to n reference pics, so the UI should be able to handle a varying number of pics.

First idea:

Presentation:
Have a "sidebar" with ref-pic thumbnails and their captions (for desktop, top/bottom-bar for mobile).
Interaction:
As long as a ref-pic is clicked/touched, it replaces/overlays the timeline-pic.

Another idea is to do this overlay with partial (adjustable?) transparency, and have a toggle to switch between no overlay, ref1, ref2, etc.
Maybe:
Shortly fully show the ref-pic on zapping, with a fade back to 100% timeline-pic. or sth. like 80% timeline-pic.

**Comment by loganbrunner** [comment]
Made some progress on the sidebar with thumbnails (for mobile, this becomes stacked and these reference thumbnails go below the main image). See commit 4a8128e3fd11d31a73727475d9b9fc0668375d3d (also merged into `main` now).

**Comment by sirtet** [comment]
> Made some progress...
Do u have a target here, that u did not reach yet?
Next planned steps?
(Would be good to know to understand better what's ready for comments and what's WIP...)

I think it looks good. 
I guess we want images to fill the available space somehow.
And i think it would be good to be able to toggle ref-pics on/off by clicking them, not only on.
Currently, interacting with them needs more focus- shifting and mouse-moving.
I would also visually highlight a currently ON ref-pic. With a border or so, or by fading out / grayscaling un-selected ref-pics.
Grayscaling might be nice. Something in spirit of a disabled UI element...
