### ISSUE TITLE
Ref picture to front when hovering

### ISSUE THREAD

**Issue by loganbrunner** [it4paddlers/river-photo-gauge#9]
Hovering over/mouseover the reference picture should superimpose the picture on the current image

**Comment by loganbrunner** [comment]
On mobile this would be holding down your finger on it.

**Comment by loganbrunner** [comment]
Added with e8be0b8. Still working on the mobile touch movements.

**Comment by sirtet** [comment]
The Update done with https://github.com/it4paddlers/river-photo-gauge/commit/e8be0b853c60672b873ccc4d544ada25d81f0554 looks good on Desktop...
On mobile, tap switches permanently... Intended or a side-effect?(It feels like a viable option too, if need be. (first idea was to revert the switching on tap-release).
If we keep this, a UI hint is missing that main-img. has to be tapped to revert to current image...
Maybe a better UI would be to revert to current img on 2nd tap of ref-img?
or even better, implement the same logic as mouse-hover, aka. show ref. while holding it?

**Comment by loganbrunner** [comment]
Yeah, this is the default touch movement for a desktop so it has just carried over to the mobile. I'll need to add different rules for the mobile, but not sure what the keywords are for it (like ontouch or when clicking it again).

The ref picture will disappear when the user clicks anywhere else on the screen other than the ref image, which is the equivalent of the desktop "onMouseEnter" (i.e. the hover)

**Comment by loganbrunner** [comment]
Look into onTouchStart and onTouchEnd - https://reactjs.org/docs/events.html#touch-events

![Screen Shot 2022-04-19 at 7 54 33 PM](https://user-images.githubusercontent.com/14346184/163953731-5be1e6cf-a464-4c62-bc0f-97dbdd683757.png)

**Comment by loganbrunner** [comment]
Looks like that worked! Added with e957565

**Comment by loganbrunner** [comment]
Merged to main. Closing for now unless an issue still remains.
